server:
  port: 8084

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/telecom
    username: root
    password: Sreeja@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cloud:
    function:
      definition: subscriptionCreated   

    stream:
      bindings:
        subscriptionCreated-in-0:
          destination: subscription-created
          group: subscription-created
          content-type: application/json

        paymentSuccess-out-0:
          destination: payment-success
          content-type: application/json

        paymentFailed-out-0:
          destination: payment-failed
          content-type: application/json

      kafka:
        binder:
          brokers: localhost:9092


stripe:
  secret:
    key: sk_test_51Sn86pDrRatGFL0K2p91dC0Dzr0LiCuLJHnBwEt3Pmxaii4ahw28jYRhLmURjkcMLTdlU41KkwhzF9CGvRHRi4LO00Zp34xJYP   
  currency: usd
